import './globals.css'
import { Manrope } from 'next/font/google'
import Script from 'next/script'
import Providers from "@/app/provider";

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'ToDo telegram WebApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
      </head>
      <body className={manrope.variable}>
      <Providers>
        <main className="wrapper">
          {children}
        </main>
      </Providers>
      </body>
      </html>
  )
}
